server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: "none"
  
spring:
  #Data Configuration  
  datasource:


    url: jdbc:postgresql://52.74.109.132:5432/giasuomt
    ##url: jdbc:postgresql://localhost/giasuomt
    username: postgres
    password: 123456
    #password: khangdeptrai
  #JPA Configuration 
  jpa:
    show-sql: true #để xem câu sql mà nó tự sinh
    generate-ddl: true #để thằng Hibernate tự nhìn Object và tạo database được
    hibernate:
      ddl-auto: update
      # ddl-auto: create-drop 
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  
      
gsomt:
  app:
    jwt-secret: apiofgsomt
    jwt-duration: 3000000 

amazon:
  accessKeyKhangAdmin: AKIAUDLYPJWXYMP46F6J                #tạo user
  secretkeyKhangAdmin: vFJP1ViiqDypQq5z6hoqQDF/46MDYxcw3GL4EJZ4
  #avatar     #   
  avatarURL: https://s3.ap-southeast-1.amazonaws.com/avatargsomt/
  bucketnameAvatar: avatargsomt
#billimage  
  billImageURL: https://s3.ap-southeast-1.amazonaws.com/billimagegsomt/
  bucketnamebillImage: billimagegsomt
#feedback
  feedbackImageURL: https://s3.ap-southeast-1.amazonaws.com/feedbackimagegsomt/
  bucketnamefeedbackImage: feedbackimagegsomt
#retainedrmgsrdentification  retainedimgsidentificationgsomt
  retainedimgsidentificationURL: https://s3.ap-southeast-1.amazonaws.com/retainedimgsidentificationgsomt/
  bucketnameretainedimgsidentification: retainedimgsidentificationgsomt 

 